name: Deploy to GitHub Pages

on:
  push:
    branches: [ 'main' ]

jobs:
  build_site:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Debug Environment
        run: |
          echo "Checking environment variables:"
          env | grep WEB3
          echo "Current directory contents:"
          ls -la

      - name: Build
        env:
          PUBLIC_WEB3FORMS_KEY: ${{ secrets.WEB3FORMS_KEY }}
        run: |
          echo "Build step starting with env:"
          env | grep WEB3
          npm run build
          echo "Build complete, checking build directory:"
          ls -la build/
          touch build/.nojekyll
          echo "dogshomefromhome.co.uk" > build/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages