name: Deploy to GitHub Pages

on:
  push:
    branches: 'main'

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20  # Updated to newer Node version
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: build
        env:
          PUBLIC_WEB3FORMS_KEY: ${{ secrets.WEB3FORMS_KEY }}  # Aligned with Shine's naming
        run: |
          npm run build
          echo "dogshomefromhome.co.uk" > build/CNAME  # Keeping your custom domain

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/'

  deploy:
    needs: build_site
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4